from abc import ABC
from .entities import Theory, TheoryBlock, TheoryType, TheorySubject
from sqlalchemy.ext.asyncio import AsyncSession
from typing import Tuple, List

class ITheoryRepository(ABC):
    async def create_theory_types_and_subjs(self, session: AsyncSession, subject2type_config: dict): ...
    async def create_theory(self, session: AsyncSession, theory: Theory): ...
    async def get_theory_by_id(self, session: AsyncSession, id: int) -> Theory: ...
    async def get_all_theories_for_subject(self, session: AsyncSession, subject_id: int) -> List[tuple[int, str]]: ...
    async def get_all_theory_dop_info(self, session: AsyncSession) -> List[dict]: ...