from abc import ABC
from .entities import Theory, TheoryBlock
from sqlalchemy.ext.asyncio import AsyncSession
from typing import Tuple, List

class ITheoryRepository(ABC):
    async def create_theory(self, session: AsyncSession, theory: Theory) -> Tuple[int, List[int]]: ...
    async def get_theory_by_id(self, session: AsyncSession, id: int) -> Theory: ...
    async def get_all_theories(self, session: AsyncSession) -> List[tuple[int, str]]: ...