from abc import ABC

from app.infra.theory.models import TaskTheoryGroupBD, TheoryBD, TheoryBlockBD
from app.core.theory.enums import BlockType
from .entities import TaskTheory, Theory, TheoryBlock, TheoryType, TheorySubject, TaskTheoryGroup
from sqlalchemy.ext.asyncio import AsyncSession
from typing import Optional, Tuple, List

class ITheoryRepository(ABC):
    async def create_theory_types_and_subjs(self, session: AsyncSession, subject2type_config: dict): ...
    async def create_theory(self, session: AsyncSession, theory: Theory, subject) -> int: ...
    async def get_theory_by_id(self, session: AsyncSession, id: int) -> Theory: ...
    async def get_all_theories_for_subject(self, session: AsyncSession, subject_id: int) -> List[tuple[int, str]]: ...
    async def get_all_theory_dop_info(self, session: AsyncSession) -> List[dict]: ...
    async def get_theories_by_names(self, session: AsyncSession, names: List[str]) -> List[TheoryBD]: ...
    async def insert_task_theory_group(self, session: AsyncSession, task_theory_group: TaskTheoryGroup): ...
    async def get_all_task_groups_for_subject(self, session: AsyncSession, subject_id: int) -> List[TaskTheoryGroupBD]: ...
    async def get_all_subjects(self, session: AsyncSession, subject_id: int | None) -> List[TheorySubject]: ...
    ###Форма
    async def create_theory_base(self, session: AsyncSession,name: str,subject: TheorySubject,type_ids: list[int]) -> TheoryBD: ...
    async def update_theory_base(self, session: AsyncSession, theory_id: int, name: Optional[str], subject: Optional[TheorySubject], type_ids: Optional[list[int]]) -> TheoryBD: ...
    async def create_block(self, session: AsyncSession, theory_id: int, type: BlockType, content: str, parent_id: Optional[int], order: int) -> TheoryBlockBD: ...
    async def update_block(self, session: AsyncSession, block_id: int, type: Optional[BlockType], content: Optional[str], parent_id: Optional[int], order: Optional[int]) -> TheoryBlockBD: ...
    async def delete_block(self, session: AsyncSession, block_id: int,) -> None: ...
    async def update_task_theory_group(self,session: AsyncSession, group_id: int, name: Optional[str], is_single: Optional[bool]) -> None: ...
    async def delete_task_theory_group(self, session: AsyncSession, group_id: int) -> None: ...
    async def insert_task_theory(self, session: AsyncSession, task: TaskTheory) -> int: ...
    async def update_task_theory(self, session: AsyncSession, task_id: int, name: Optional[str], group_id: Optional[int]) -> None: ...
    async def delete_task_theory(self, session: AsyncSession, task_id: int) -> None: ...
    async def replace_task_theory_links(self, session: AsyncSession, task_id: int, theory_ids: list[int]) -> None: ...
    async def insert_task_theory_group_from_request(self, session: AsyncSession, task_theory_group: TaskTheoryGroup ): ...