version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - host=${host}
      - user=${user}
      - password=${password}
      - db=${db}
      - port=${port}
    working_dir: /app
    command: python -m app
    ports:
    - "8000:8000"
    mem_limit: 512m
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - appnet


  tg_bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      - TOKEN=${TOKEN}
      - WEB_APP_URL=${WEB_APP_URL}
      - API_URL=http://localhost:8000/api
    working_dir: /app
    command: python main.py
    restart: unless-stopped
    mem_limit: 256m
    depends_on:
      - backend 
    network_mode: "host"

networks:
  appnet:
    driver: bridge

