"""rebuild tasks, add timestamps

Revision ID: 02466c149f49
Revises: 684070b46754
Create Date: 2026-03-13 08:53:16.487762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '02466c149f49'
down_revision: Union[str, Sequence[str], None] = '684070b46754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=256), nullable=False),
    sa.Column('extras', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('option_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainer_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('second_name', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('option_set2option',
    sa.Column('option_set_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['option.id'], ),
    sa.ForeignKeyConstraint(['option_set_id'], ['option_set.id'], ),
    sa.PrimaryKeyConstraint('option_set_id', 'option_id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('trainer_type_fk', sa.Integer(), nullable=False),
    sa.Column('default_option_set_fk', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_option_set_fk'], ['option_set.id'], ),
    sa.ForeignKeyConstraint(['trainer_type_fk'], ['trainer_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_raw', sa.Text(), nullable=False),
    sa.Column('content_visible', sa.Text(), nullable=False),
    sa.Column('content_correct', sa.Text(), nullable=False),
    sa.Column('correct_option_fk', sa.Integer(), nullable=True),
    sa.Column('option_set_override_fk', sa.Integer(), nullable=True),
    sa.Column('notice_wrong', sa.Text(), nullable=True),
    sa.Column('notice_right', sa.Text(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['correct_option_fk'], ['option.id'], ),
    sa.ForeignKeyConstraint(['option_set_override_fk'], ['option_set.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_mistakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_fk', sa.Integer(), nullable=False),
    sa.Column('mistake_item_fk', sa.Integer(), nullable=False),
    sa.Column('chosen_option_fk', sa.Integer(), nullable=False),
    sa.Column('task_session_fk', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chosen_option_fk'], ['option.id'], ),
    sa.ForeignKeyConstraint(['mistake_item_fk'], ['task_item.id'], ),
    sa.ForeignKeyConstraint(['task_session_fk'], ['task_session.id'], ),
    sa.ForeignKeyConstraint(['user_fk'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task_theory', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('task_theory', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('task_theory2theory', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('task_theory2theory', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('task_theory_group', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('task_theory_group', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('theory', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('theory', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('theory_block', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('theory_block', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('theory_block', 'type',
               existing_type=mysql.ENUM('title', 'subtitle', 'rule', 'example', 'exception', 'important', 'text', 'svg', 'group', 'link', 'note'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('theory_block', 'type',
               existing_type=mysql.ENUM('title', 'subtitle', 'rule', 'example', 'exception', 'important', 'text', 'svg', 'group', 'link', 'note'),
               nullable=False)
    op.drop_column('theory_block', 'updated_at')
    op.drop_column('theory_block', 'created_at')
    op.drop_column('theory', 'updated_at')
    op.drop_column('theory', 'created_at')
    op.alter_column('task_theory_group', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_column('task_theory_group', 'updated_at')
    op.drop_column('task_theory_group', 'created_at')
    op.drop_column('task_theory2theory', 'updated_at')
    op.drop_column('task_theory2theory', 'created_at')
    op.alter_column('task_theory', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_column('task_theory', 'updated_at')
    op.drop_column('task_theory', 'created_at')
    op.drop_table('user_mistakes')
    op.drop_table('task_session')
    op.drop_table('task_item')
    op.drop_table('task')
    op.drop_table('option_set2option')
    op.drop_table('user')
    op.drop_table('trainer_type')
    op.drop_table('option_set')
    op.drop_table('option')
    # ### end Alembic commands ###
