"""made chosen option fk optional

Revision ID: 07bddd0f12cf
Revises: 7166b94db8e3
Create Date: 2026-03-20 18:00:53.262717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '07bddd0f12cf'
down_revision: Union[str, Sequence[str], None] = '7166b94db8e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_mistakes', 'chosen_option_fk',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('user_mistakes', 'chosen_option_override',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_mistakes', 'chosen_option_override',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('user_mistakes', 'chosen_option_fk',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
