"""made field group fror task optional

Revision ID: 518de550c0bb
Revises: 930d06daf2ac
Create Date: 2026-03-13 15:39:23.795369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '518de550c0bb'
down_revision: Union[str, Sequence[str], None] = '930d06daf2ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'task_group_fk',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'task_group_fk',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
