"""some updates with task group + added trainer_type

Revision ID: 67faaa754e56
Revises: 518de550c0bb
Create Date: 2026-03-17 18:45:35.658325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '67faaa754e56'
down_revision: Union[str, Sequence[str], None] = '518de550c0bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('task_ibfk_2'), 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'task_group', ['task_group_fk'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key(op.f('task_ibfk_2'), 'task', 'task_group', ['task_group_fk'], ['id'])
    # ### end Alembic commands ###
