"""add chosen_option_override to user_mistakes

Revision ID: 7166b94db8e3
Revises: 67faaa754e56
Create Date: 2026-03-20 17:41:49.811326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7166b94db8e3'
down_revision: Union[str, Sequence[str], None] = '67faaa754e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_mistakes', sa.Column('chosen_option_override', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('user_mistakes', 'chosen_option_extra')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_mistakes', sa.Column('chosen_option_extra', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('user_mistakes', 'chosen_option_override')
    # ### end Alembic commands ###
