"""added closed_at field to sessions and some staff to user and mistakes tables

Revision ID: 930d06daf2ac
Revises: f0e7381bf145
Create Date: 2026-03-13 10:45:31.461902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '930d06daf2ac'
down_revision: Union[str, Sequence[str], None] = 'f0e7381bf145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_session', sa.Column('closed_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('avatar_url', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('last_active_at', sa.DateTime(), nullable=True))
    op.add_column('user_mistakes', sa.Column('is_resolved', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_mistakes', 'is_resolved')
    op.drop_column('user', 'last_active_at')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'birth_date')
    op.drop_column('user', 'avatar_url')
    op.drop_column('user', 'username')
    op.drop_column('task_session', 'closed_at')
    # ### end Alembic commands ###
