"""rename trainer_type to trainer_group

Revision ID: f0e7381bf145
Revises: 02466c149f49
Create Date: 2026-03-13 09:26:06.943088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f0e7381bf145'
down_revision: Union[str, Sequence[str], None] = '02466c149f49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    
    # ← Сначала убираем FK и старую колонку с task
    op.drop_constraint(op.f('task_ibfk_2'), 'task', type_='foreignkey')
    op.drop_column('task', 'trainer_type_fk')
    
    # ← Теперь можно дропать trainer_type — никто не ссылается
    op.drop_table('trainer_type')
    
    # ← Добавляем новую колонку и FK
    op.add_column('task', sa.Column('task_group_fk', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task', 'task_group', ['task_group_fk'], ['id'])



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('trainer_type_fk', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key(op.f('task_ibfk_2'), 'task', 'trainer_type', ['trainer_type_fk'], ['id'])
    op.drop_column('task', 'task_group_fk')
    op.create_table('trainer_type',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
